-- V1：初始化每日一句核心表与约束
-- 本文件只负责数据结构，不写入任何业务数据；兜底种子由 V2 负责。

BEGIN;

-- 语录表：正文/出处/背景图为读者端四要素中的三项，均不允许为空。
-- 展示日期用 DATE 存储，发布时间语义由 status 与 display_date 共同表达。
CREATE TABLE IF NOT EXISTS quote (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content           VARCHAR(60)  NOT NULL,
    source            VARCHAR(120) NOT NULL,
    display_date      DATE         NOT NULL,
    background_image  VARCHAR(500) NOT NULL,
    status            VARCHAR(16)  NOT NULL DEFAULT 'draft',
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_quote_content_not_blank CHECK (length(btrim(content)) > 0),
    CONSTRAINT ck_quote_source_format CHECK (source ~ '^《[^》]+》—— .+$'),
    CONSTRAINT ck_quote_status CHECK (status IN ('draft', 'published'))
);

-- 每个展示日期最多一条已上架语录；草稿可存在多条，保留运营试稿空间。
CREATE UNIQUE INDEX IF NOT EXISTS uk_quote_published_display_date
    ON quote (display_date)
    WHERE status = 'published';

-- 更新时自动刷新 updated_at，保证已发布内容变动可追溯。
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_quote_updated_at ON quote;
CREATE TRIGGER trg_quote_updated_at
    BEFORE UPDATE ON quote
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- 系统配置表：保存兜底语录内容等运营预置数据，避免兜底逻辑硬编码在应用中。
CREATE TABLE IF NOT EXISTS system_config (
    config_key    VARCHAR(64)  PRIMARY KEY,
    config_value  TEXT         NOT NULL,
    description   VARCHAR(255),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP
);

DROP TRIGGER IF EXISTS trg_system_config_updated_at ON system_config;
CREATE TRIGGER trg_system_config_updated_at
    BEFORE UPDATE ON system_config
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

COMMIT;
